Repository ArkEcosystem/multisig-server, pull requests merged in 2020-03, with the labels that each got.

#51 chore: include network name in sqlite db name
  __tests__/server/server.test.ts
  packages/server/src/index.ts
  packages/server/src/server/index.ts
Labels: Complexity: Medium, Type: Task

#55 ci: drop node 10 and 11 for tests
  .github/workflows/test.yml
Labels: Complexity: Low

#54 feat: add network height cli parameter
  packages/cli/src/commands/command.ts
  packages/server/src/server/index.ts
Labels: Complexity: Low, Type: Feature
